### ISSUE TITLE
Support for CodeUri and AWS::Serverles::*

### ISSUE THREAD

**Issue by austinried** [cloudtools/stacker#580]
I'm new to stacker and trying to set up some tests to see if it's going to work with our setup, but unless I'm missing something it appears that support for the Serverless resource types is missing, specifically support for packaging Lambda functions to an S3 bucket and replacing the CodeUri attribute with the S3 key.  I have found that there is very similar support for the Code attribute in the non-Serverless version of function via this hook: http://stacker.readthedocs.io/en/latest/api/stacker.hooks.html#module-stacker.hooks.aws_lambda but that seems to only be for `troposphere.awslambda.Function` and not for `troposphere.serverless.Function`.

Is support for the Serverless version of Lambda upload coming or planned, or am I missing the piece that gets it to work?

**Comment by austinried** [comment]
Ah actually I've just realized I can use the returned `Code` object to build the S3 `CodeUri` myself:

```python
def create_template(self):
    t = self.template
    t.transform = 'AWS::Serverless-2016-10-31'
    code = self.context.hook_data['lambda']['MyFunction']
    
    t.add_resource(serverless.Function(
        'LambdaFunction',
        CodeUri='s3://' + code.S3Bucket + '/' + code.S3Key,
        Handler='my_handler',
        Runtime='python2.7',
        Timeout=60,
    ))
```

So that seems to get the job done, would be nice if there were some sort of official support though.

**Comment by phobologic** [comment]
Hey @austinried - thanks for the issue, and sorry for not responding sooner.  Glad you found the work-around you mentioned.  It would take some work, but I could imagine extending the hook_data so that it contained both the Code object, as well as the S3 URI.  It's a little strange because we made the current return only the Code object, rather than a dictionary containing the Code object (which would have been more extendable).

Another option is for us to subclass the Code object from troposphere in this hook, and add an extra method/property to it which will return the S3.  Any thoughts?

@danielkza you were the original author of the hook, any thoughts?

**Comment by danielkza** [comment]
@phobologic At the time I didn't consider more information could be added, as Serverless was not supported in Cloudformation. Returning a custom subclass of `Code` seems like a fine solution for now, but it might be a good idea to add a deprecation notice, and eventually move to something more flexible like a `dict` (containing both the `Code` and any other relevant attributes).

**Comment by phobologic** [comment]
I'm going to go ahead and close this - I think what we have now can work just fine.  You can use the `hook_data` lookup to pass the `Code` object into the blueprint, and from there you can use attribute access to build other objects, ie:

```
s3_key = code_obj.S3Key
s3_bucket = code_obj.S3Bucket
```

etc

Let me know if that doesn't make sense, or if I'm missing some other use case.  Thanks!
